spring:
  application:
    name: pebble-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pebble}
    username: ${DB_USERNAME:pebble}
    password: ${DB_PASSWORD:pebble-local}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
